spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: root
    password: test
    url: jdbc:mysql://root@:3306/dev_pub?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    #?allowPublicKeyRetrieval=true&useSSL=false

  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yml

